config/routes.rb
PerfectDay::Application.routes.draw do
 match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
 match 'auth/failure', to: redirect('/'), via: [:get, :post]
 match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


 root to: "sessions#index"
 resources :users
 resources :favorites, except: :destroy
 delete '/destroy_favorite' => "favorites#destroy", as: 'destroy_favorite'
 get '/search' => "itineraries#search"
 get '/browse' => "itineraries#browse"
 get '/new' => "itineraries#new"
 post '/create' => "itineraries#create"
 resources :itineraries, except: [:browse,:new,:favorite,:create] do
  resources :spots
 end

 post '/find_location'  => "sessions#geolocate"
 # get '/upvote/itin/:id' => "itineraries#upvote"
 # get '/upvote/spot/:id' => "spots#upvote"
 get '/data/spot_types.json' => 'spots#spot_types'
 get '/spots/:id' => 'spots#single_spot'
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :user
  has_many :itinerary_spots
  has_many :spots, through: :itinerary_spots

  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user

  # def upvote!
  #   self.vote_count += 1
  #   self.save
  # end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  def index
  end

  def browse
    @itineraries = Itinerary.all
    @distances = {}
    @itineraries.each do |itin|
      distance = Haversine.distance(session[:coords][0], session[:coords][1],
                    itin.spots[0].coords[0], itin.spots[0].coords[1]).to_miles
      @distances[distance] = itin
    end
    @distances = @distances.sort_by {|k,v| k}
    @distances = Hash[*@distances.flatten]
  end

  def create
    user_itinerary = Itinerary.find_or_create_by(name: params[:name])
    current_user.itineraries << user_itinerary
    params[:spots].each do |key,value|
      spot = Spot.find_or_create_by(name: value[:name], address: value[:address],
                                    phone: value[:phone], latitude: value[:latitude],
                                    longitude: value[:longitude])
      user_itinerary.spots << spot
      itinerary_spot = spot.itinerary_spots.find_by_itinerary_id(user_itinerary.id)
      itinerary_spot.update_attributes(description: value[:description])

      value[:types].each do |type|
        spot.spot_types << SpotType.find_or_create_by(name: type)
      end
    end

    redirect_to user_path(current_user)
  end

  def new
  end

  def spot
  end

  def search
    @spot_type = SpotType.where(name: params[:name]).includes(:spots).pop
    @distances = {}
    if @spot_type
      @spot_type.spots.each do |spot|
        distance = Haversine.distance(session[:coords][0], session[:coords][1],
                      spot.coords[0], spot.coords[1]).to_miles
        @distances[distance] = spot
      end
      @distances = @distances.sort_by {|k,v| k}
      @distances = Hash[*@distances.flatten]
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])
  end

  # def upvote
  #   itin = Itinerary.find(params[:id])
  #   itin.upvote!
  #   redirect_to(:back)
  # end
end

app/views/itineraries/_itineraries_template.html.erb
<div class="itineraries">

  <% @itineraries.try(:each) do |itinerary| %>
    <a href="/itineraries/<%= itinerary.id %>/spots/<%= itinerary.spots.first.id %>"><%= itinerary.name %></a><br>
    <% waypoints = [] %>

    <% itinerary.spots.each do |spot| %>
      <% waypoints << [spot.latitude.to_f, spot.longitude.to_f] %>
    <% end %>

    <div class="map-canvas" data-latlong='<%= waypoints %>' style="width:300px;height:250px;margin:0 auto;display:block;"></div>
  <% end %>

</div>

app/views/itineraries/_spot.html.erb
<fieldset>
  <label>Spot Address<input class="address" type="text" name="itineraries_name[][address]"></label>
  <label>Spot Description<input class="description" type="text" name="itineraries_name[][description]"></label>
</fieldset>

app/views/itineraries/browse.html.erb
<div class="row map_holder">
  <div class="itineraries">

    <% @distances.try(:each) do |distance, itinerary| %>
      
      <% waypoints = [] %>

      <% itinerary.spots.each do |spot| %>
        <% waypoints << [spot.latitude.to_f, spot.longitude.to_f] %>
      <% end %>

      <div class="large-12 perfect_day_list">
        <a href="/itineraries/<%= itinerary.id %>/spots/<%= itinerary.itinerary_spots.first.id %>" class="day_title"><%= itinerary.name %></a>
        <div class="map_background">
          <span class="itinerary_score" style="font-size: 0.8em; padding: 2px 10px; font-weight: 400; top: -32px;"><%= distance.round(2) %> mi.</span>
          <div class="map-canvas" data-latlong='<%= waypoints %>' style="width:100%;height:250px;display:block;"></div>

          <ul class="tags">
            <% itinerary.itinerary_spots.each do |itinerary_spot| %>
             <li><a><%= Spot.find(itinerary_spot.spot_id).name %></a></li>
            <% end %>
          </ul>
        </div>  
      </div>
    <% end %>

  </div>
</div>

app/views/itineraries/new.html.erb
<div class="row map_holder">
	<%= form_for :itineraries, url: create_path, html: {id: 'create_itinerary_form'} do |f| %>
	  <%= f.label :name, "name your itinerary" %>
	  <%= f.text_field :name %>
	  <%= render "spot" %>
	  <button id="add_new_spot" type="button">Add New Spot</button>
	  <%= f.submit "Publish" %>
	<% end %>
</div>

app/views/itineraries/search.html.erb
<div class="row map_holder">

    <!-- Make this form a form helper -->
    <form id="search" action="/search" method="GET">
      <input id="spot_type_search_input" class="typeahead tt-query" type="text" placeholder="Search Categories" autocomplete="off" spellcheck="false" dir="auto" name="name">
      <span class="tt-dropdown-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none; right: auto;"></span>
      <button type="submit">Search</button>
    </form>
    <!-- end comment -->

  <% if @spot_type %>
    <% @distances.each do |distance, spot| %>
      <div class="large-12 perfect_day_list">
    
        <a href="spots/<%= spot.id %>" class="day_title"><%= spot.name %></a>
        
        <div class="map_background">
          <span class="itinerary_score" style="font-size: 0.8em; padding: 2px 10px; font-weight: 400; top: -32px;"><%= distance.round(2) %> mi.</span>
          <div class="spots search-results">
             <div class="map-canvas" data-lat='<%=spot.latitude.to_f%>' data-name='<%=spot.name%>' data-long='<%=spot.longitude.to_f%>' style="width:100%;height:250px;display:block;"></div>
          </div>
        </div>

        <div class="small-12 spot_address" style="margin-top: 10px;"><i class="fa fa-map-marker"></i> <%= spot.address %></div>
        <div class="small-12 spot_address"><i class="fa fa-phone"></i> <%= spot.phone %></div>

      </div>
    <% end %>
  <% end %>
</div>

app/views/itineraries/show.html.erb
<h1><%= @itinerary.name %></h1>
<a href='/upvote/itin/<%= @itinerary.id %>'><button data=<%= @itinerary.id %> type='button'>Upvote</button></a><%= @itinerary.vote_count %>

<h2>Spots</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Description</th>
    <th>Upvote</th>
  </tr>
  <% @itinerary.spots.each do |spot| %>
    <tr>
      <td><%= spot.name %></td>
      <td><%= spot.address%></td>
      <td><%= spot.itinerary_spots.find_by_itinerary_id(@itinerary.id).description %></td>
    </tr>
  <% end %>
</table>