config/routes.rb
PerfectDay::Application.routes.draw do
 match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
 match 'auth/failure', to: redirect('/'), via: [:get, :post]
 match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


 root to: "sessions#index"
 resources :users
 resources :favorites, except: :destroy
 delete '/destroy_favorite' => "favorites#destroy", as: 'destroy_favorite'
 get '/search' => "itineraries#search"
 get '/browse' => "itineraries#browse"
 get '/new' => "itineraries#new"
 post '/create' => "itineraries#create"
 resources :itineraries, except: [:browse,:new,:favorite,:create] do
  resources :spots
 end

 post '/find_location'  => "sessions#geolocate"
 # get '/upvote/itin/:id' => "itineraries#upvote"
 # get '/upvote/spot/:id' => "spots#upvote"
 get '/data/spot_types.json' => 'spots#spot_types'
 get '/spots/:id' => 'spots#single_spot'
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_many :itinerary_spots
  has_many :itineraries, through: :itinerary_spots
  has_and_belongs_to_many :spot_types

  # def upvote!
  #   self.vote_count += 1
  #   self.save
  # end

  def coords
    [self.latitude.to_f, self.longitude.to_f]
  end

end

app/models/spot_type.rb
class SpotType < ActiveRecord::Base
  has_and_belongs_to_many :spots
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
  end

  def show
    @itinerary = Itinerary.find(params[:itinerary_id])
    @itin_spot = ItinerarySpot.find(params[:id])
    @spot = Spot.find(@itin_spot.spot_id)
  end

  def create
  end

  # def upvote
  #   spot = Spot.find(params[:id])
  #   spot.upvote!
  #   redirect_to(:back)
  # end

  def spot_types
    render json: SpotType.pluck(:name)
  end

  def single_spot
    @spot = Spot.find(params[:id])

    @itineraries_with_current_spot = @spot.itineraries

    @next_spots = []

    @itineraries_with_current_spot.each do |itinerary|
      itinerary_spots = itinerary.itinerary_spots
      current_itin_spot_index = itinerary_spots.index {|it_spot| it_spot.spot_id == @spot.id}
      next_itin_spot_index = current_itin_spot_index + 1
      last_index_number = itinerary.itinerary_spots.count - 1
      unless next_itin_spot_index > last_index_number
        next_itin_spot = itinerary_spots[next_itin_spot_index]
        next_spot = Spot.find(next_itin_spot.spot_id)
        @next_spots << next_spot
      end
    end

    @distances = {}
    @next_spots.each do |spot|
      distance = Haversine.distance(session[:coords][0], session[:coords][1],
                    spot.coords[0], spot.coords[1]).to_miles
      @distances[spot.name] = distance
    end
    @distances = @distances.sort_by {|spot_name,distance| distance}.first(3)
  end

end

app/views/spots/show.html.erb
<div class="row">
	<div class="small-12 itin_header">
			<h1 class="itin_title small-10 column"><%= @itinerary.name %></h1>

			<div class="favorite small-2 column">
				<%  if current_user %>
				  <% if current_user.has_favorited?(@itinerary) %>
				    <%= link_to "unfavorite", destroy_favorite_path(itinerary_id: @itinerary.id), method: :delete %>
				  <% else %>
				  <%= link_to "favorite", favorites_path(itinerary_id: @itinerary.id), method: :post %>
				  <% end %>
				<% end %>
			</div>
	</div>
</div>

	<div class="large-12 perfect_day_list no_dash_border" style="padding-bottom: 70px;">

		<div class="spot_title">
			<%= @spot.name %>
		</div>
		
		<div class="spots search-results map_background">
		  <div class="map-canvas" data-lat='<%=@spot.latitude%>' data-name='<%=@spot.name%>' data-long='<%=@spot.longitude%>' style="width:100%;height:250px;margin:0 auto;display:block;"></div>
		</div>

		<div class="small-12 spot_address" style="margin-top: 10px;"><i class="fa fa-map-marker"></i> <%= @spot.address %></div>
		<div class="small-12 spot_address"><i class="fa fa-phone"></i> <%= @spot.phone %></div>

		<span class="small-12 separator"></span>

		<div class="row separator">
			<h3 style="margin: 0;font: normal 1em 'Open Sans';font-weight: 600;">Description:</h3>
			<p style="margin: 5px 0 0 0;font: normal 0.8em 'Open Sans';font-weight: 400;"><%= @itin_spot.description %></p>
		</div>

		<div class="row separator ">
			<h3 style="margin: 0;font: normal 1em 'Open Sans';font-weight: 600;">Spots on This Itinerary:</h3>	
	  </div>

	  <ul class="row next_spot_holder">
	    <% @itinerary.itinerary_spots.each do |itinerary_spot| %>
	      <li class="small-12 the_spots">
	      	<a href="/itineraries/<%= Itinerary.find(itinerary_spot.itinerary_id).id %>/spots/<%= itinerary_spot.id %>"><%= Spot.find(itinerary_spot.spot_id).name %></a>
	      </li>
	    <% end %>
	  </ul>
	</div>

app/views/spots/single_spot.html.erb
<div class="map_holder">

  <div class="large-12 perfect_day_list no_dash_border" style="padding-bottom: 70px;">
      
      <div class="spot_title">
        <%= @spot.name %>
      </div>

      <div class="spots search-results map_background">
        <div class="map-canvas" data-lat='<%=@spot.latitude%>' data-name='<%=@spot.name%>' data-long='<%=@spot.longitude%>' style="width:100%;height:250px;margin:0 auto;display:block;"></div>
      </div>

      <div class="small-12 spot_address" style="margin-top: 10px;"><i class="fa fa-map-marker"></i> <%= @spot.address %></div>
      <div class="small-12 spot_address"><i class="fa fa-phone"></i> <%= @spot.phone %></div>

      <span class="small-12 separator"></span>

      <div class="row separator">
        <h3 style="margin: 0;font: normal 1em 'Open Sans';font-weight: 600;">Popular Next Spots:</h3>
      </div>

      <ul class="row next_spot_holder">
        <% unless @distances.empty? %>
        <% @distances.each do |spot_name,distance| %>
          <li class="small-12 the_spots">
            <a href="/spots/<%= Spot.find_by_name(spot_name).id %>"><%= spot_name %></a> <span style="font-size: 0.8em">(<%= distance.round(1) %> mi.)</span>
          </li>
        <% end %>
        <% end %>
      </ul>
  </div>
    
</div>