config/routes.rb
PerfectDay::Application.routes.draw do
 match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
 match 'auth/failure', to: redirect('/'), via: [:get, :post]
 match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]


 root to: "sessions#index"
 resources :users
 resources :favorites, except: :destroy
 delete '/destroy_favorite' => "favorites#destroy", as: 'destroy_favorite'
 get '/search' => "itineraries#search"
 get '/browse' => "itineraries#browse"
 get '/new' => "itineraries#new"
 post '/create' => "itineraries#create"
 resources :itineraries, except: [:browse,:new,:favorite,:create] do
  resources :spots
 end

 post '/find_location'  => "sessions#geolocate"
 # get '/upvote/itin/:id' => "itineraries#upvote"
 # get '/upvote/spot/:id' => "spots#upvote"
 get '/data/spot_types.json' => 'spots#spot_types'
 get '/spots/:id' => 'spots#single_spot'
end

app/views/layouts/_footer_nav.html.erb
<% if current_user %>

  <div class='row footer_nav'>
    <div class="small-12">
      <div class="small-2 columns" style="width: 20%;">
        <%= link_to '', user_path(current_user), class: "fa fa-home" %>
      </div>

      <div class="small-2 columns" style="width: 20%;">
        <%= link_to '', browse_path, class: "fa fa-compass" %>
      </div>

      <div class="small-2 columns" style="width: 20%;">
        <%= link_to '', new_path, class: "fa fa-map-marker" %>
      </div>

      <div class="small-2 columns" style="width: 20%;">
        <%= link_to '', favorites_path, class: "fa fa-heart" %>
      </div>

      <div class="small-2 columns" style="width: 20%;">
        <%= link_to '', search_path, class: "fa fa-search" %>
      </div>
    </div>
  </div>
  
  <% elsif current_page?('/') %>
  
  <% else %>

    This is navi-footer.

<% end %>

app/views/layouts/_header.html.erb
<% if current_user %>

  <!-- this will be on the options popout on top nav -->
  <div class="row header">
    <div class="small-6 columns small_logo">
      Perfect Day
    </div>
    <div class="small-6 columns" style="text-align: right;">
      <%= image_tag current_user.profile_url, class: "user_avatar" %>
      <%= link_to "Sign Out", signout_path(current_user), method: :destroy, class: "sign_out" %>
    </div>
  </div>

  <% elsif current_page?('/') %>

  <% else %>

  <div class="row" style="background: #eee;">
    <div class="small-12">
      Header Goes Here.
    </div>
  </div>

<% end %>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, user-scalable=false, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Perfect Day" %></title>

  	<%= stylesheet_link_tag    "application" %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <%= yield %>


    <%= render "layouts/footer_nav" %>


    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtt4-lM1MBQ1Utw1m7aXtyLh2DZZLbRrM&sensor=false&libraries=places"></script>

    <%= javascript_include_tag "application" %>
  </body>
</html>